apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: special-system
  annotations:
    skip: "false" # set to true and apply to delete the deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80