apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: default
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: default
spec:
  secretName: admission-server-certs
  dnsNames:
    - admission-server.default.svc
    - admission-server.default.svc.cluster.local
  issuerRef:
    name: selfsigned-issuer
