apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-server
  labels:
    app: admission-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission-server
  template:
    metadata:
      labels:
        app: admission-server
    spec:
      containers:
        - name: server
          image: us.icr.io/gitsecure/tkn-admcontroller:0.3.0
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8443
              scheme: HTTPS
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: tls-certs
              mountPath: /etc/certs
              readOnly: true
            - name: cosign-pub-key
              mountPath: /etc/cosign
              readOnly: true
      imagePullSecrets:
        - name: icr-registry-key
      volumes:
        - name: tls-certs
          secret:
            secretName: admission-server-certs
        - name: cosign-pub-key
          secret:
            secretName: cosign-pub 
---
apiVersion: v1
kind: Service
metadata:
  name: admission-server
spec:
  selector:
    app: admission-server
  ports:
    - port: 443
      targetPort: 8443
