apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pipelinerun-validation
  annotations:
    cert-manager.io/inject-ca-from: default/selfsigned-cert
webhooks:
  - name: pipelinerun-validation.default.svc
    clientConfig:
      service:
        name: admission-server
        namespace: default
        path: '/validate/pipelineruns'
      caBundle: '${CA_BUNDLE}'
    rules:
      - operations: ['CREATE']
        apiGroups: ['tekton.dev']
        apiVersions: ['v1beta1']
        resources: ['pipelineruns']
    failurePolicy: Fail
    admissionReviewVersions: ['v1beta1']
    sideEffects: None
    timeoutSeconds: 5
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: task-validation
  annotations:
    cert-manager.io/inject-ca-from: default/selfsigned-cert
webhooks:
  - name: task-validation.default.svc
    clientConfig:
      service:
        name: admission-server
        namespace: default
        path: '/validate/tasks'
      caBundle: '${CA_BUNDLE}'
    rules:
      - operations: ['CREATE']
        apiGroups: ['tekton.dev']
        apiVersions: ['v1beta1']
        resources: ['tasks']
    failurePolicy: Fail
    admissionReviewVersions: ['v1beta1']
    sideEffects: None
    timeoutSeconds: 5
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: taskrun-validation
  annotations:
    cert-manager.io/inject-ca-from: default/selfsigned-cert
webhooks:
  - name: taskrun-mutation.default.svc
    clientConfig:
      service:
        name: admission-server
        namespace: default
        path: '/validate/taskruns'
      caBundle: '${CA_BUNDLE}'
    rules:
      - operations: ['CREATE']
        apiGroups: ['tekton.dev']
        apiVersions: ['v1beta1']
        resources: ['taskruns']
    failurePolicy: Fail
    admissionReviewVersions: ['v1beta1']
    sideEffects: None
    timeoutSeconds: 5
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pipeline-validation
  annotations:
    cert-manager.io/inject-ca-from: default/selfsigned-cert
webhooks:
  - name: pipeline-validation.default.svc
    clientConfig:
      service:
        name: admission-server
        namespace: default
        path: '/validate/pipelines'
      caBundle: '${CA_BUNDLE}'
    rules:
      - operations: ['CREATE']
        apiGroups: ['tekton.dev']
        apiVersions: ['v1beta1']
        resources: ['pipelines']
    failurePolicy: Fail
    admissionReviewVersions: ['v1beta1']
    sideEffects: None
    timeoutSeconds: 5
