apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    cosign.sigstore.dev/message: "message"
    cosign.sigstore.dev/signature: "signature"
  name: test-pipeline 
spec:
  tasks:
    - name: goodbye
      taskRef:
        name: goodbye
