apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    ossc.sigstore.tapestry.dev/transparency: "rekor://my-reckor-log/index"
  name: test-pipeline 
spec:
  tasks:
    - name: goodbye
      taskRef:
        name: goodbye
